name: Capture Webpage Screenshot

on:
  push:
  schedule:
    - cron: "*/5 14-23,0-5 * * *"
    - cron: "5 6-13 * * *"

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Capture Screenshot
        run: node capture-screenshot.js

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

      - name: Upload Screenshot to S3
        run: |
            aws s3 cp screenshot.png s3://np-screenshot/screenshot.png --region us-west-2
            aws s3api put-object-tagging --bucket np-screenshot --key screenshot.png --tagging 'TagSet=[{Key=public,Value=yes}]' --region us-west-2